-- Aula 02 - Criando as tabelas
-- Enunciado: exercicios/enunciados/aula02-ddl.md
--
-- Escreva a resposta de cada exercicio embaixo do marcador dele.
-- Nao apague os marcadores, nao troque a ordem.
-- Cada bloco roda num banco em branco: crie o que voce for usar.

-- ex1
CREATE TABLE LIVRO (
    ID INTEGER PRIMARY KEY,
    TITULO TEXT NOT NULL,
    AUTOR TEXT NOT NULL,
    ANO INTEGER,
    EXEMPLARES INTEGER NOT NULL DEFAULT 1
);

INSERT INTO LIVRO (ID, TITULO, AUTOR, ANO)
VALUES (1, 'O Guarani', 'Jose de Alencar', 1857);

INSERT INTO LIVRO (ID, TITULO, AUTOR, ANO, EXEMPLARES)
VALUES (2, 'A Hora da Estrela', 'Clarice Lispector', 1977, 4);

-- ex2
CREATE TABLE LEITOR (
    ID INTEGER PRIMARY KEY,
    NOME TEXT NOT NULL
);

INSERT INTO LEITOR (ID, NOME) VALUES (1, 'Maria');
INSERT INTO LEITOR (ID, NOME) VALUES (2, 'Lucas');
INSERT INTO LEITOR (ID, NOME) VALUES (3, 'Sofia');

ALTER TABLE LEITOR ADD COLUMN TELEFONE TEXT;

SELECT * FROM LEITOR;

-- ex3
CREATE TABLE EMPRESTIMO (
    ID INTEGER PRIMARY KEY,
    ID_LIVRO INTEGER NOT NULL
);

INSERT INTO EMPRESTIMO (ID, ID_LIVRO) VALUES (1, 10);
INSERT INTO EMPRESTIMO (ID, ID_LIVRO) VALUES (2, 20);

ALTER TABLE EMPRESTIMO
ADD COLUMN SITUACAO TEXT NOT NULL DEFAULT 'Nao informada';

-- ex4
CREATE TABLE EDITORA (
    ID INTEGER PRIMARY KEY,
    NM TEXT
);

INSERT INTO EDITORA (ID, NM) VALUES (1, 'Horizonte Editorial');

ALTER TABLE EDITORA RENAME COLUMN NM TO NOME;

-- ex5
CREATE TABLE RASCUNHO (
    ID INTEGER PRIMARY KEY,
    TEXTO TEXT
);

INSERT INTO RASCUNHO (ID, TEXTO) VALUES (1, 'Anotacao de Maria');
INSERT INTO RASCUNHO (ID, TEXTO) VALUES (2, 'Lista de livros');
INSERT INTO RASCUNHO (ID, TEXTO) VALUES (3, 'Rascunho da biblioteca');

DELETE FROM RASCUNHO;

SELECT * FROM RASCUNHO;

DROP TABLE RASCUNHO;

-- ex6
PRAGMA foreign_keys = ON;

CREATE TABLE LIVRO (
    ID INTEGER PRIMARY KEY,
    TITULO TEXT NOT NULL
);

CREATE TABLE LEITOR (
    ID INTEGER PRIMARY KEY,
    NOME TEXT NOT NULL
);

CREATE TABLE EMPRESTIMO (
    ID_LIVRO INTEGER NOT NULL,
    ID_LEITOR INTEGER NOT NULL,
    DATA_SAIDA TEXT NOT NULL,
    DATA_VOLTA TEXT,
    PRIMARY KEY (ID_LIVRO, ID_LEITOR, DATA_SAIDA),
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO (ID),
    FOREIGN KEY (ID_LEITOR) REFERENCES LEITOR (ID)
);

INSERT INTO LIVRO (ID, TITULO) VALUES (1, 'Inventario das Nuvens');
INSERT INTO LIVRO (ID, TITULO) VALUES (2, 'Atlas do Bosque');
INSERT INTO LEITOR (ID, NOME) VALUES (1, 'Maria');
INSERT INTO LEITOR (ID, NOME) VALUES (2, 'Tiago');

INSERT INTO EMPRESTIMO (ID_LIVRO, ID_LEITOR, DATA_SAIDA, DATA_VOLTA)
VALUES (1, 1, '2026-08-04', '2026-08-12');

INSERT INTO EMPRESTIMO (ID_LIVRO, ID_LEITOR, DATA_SAIDA, DATA_VOLTA)
VALUES (1, 1, '2026-08-19', NULL);

-- Deve ser recusado: repete livro, leitor e data_saida, que formam a chave primaria.
-- INSERT INTO EMPRESTIMO (ID_LIVRO, ID_LEITOR, DATA_SAIDA, DATA_VOLTA)
-- VALUES (1, 1, '2026-08-04', '2026-08-14');
